/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationRouteImport } from './routes/station'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedSujetsRouteImport } from './routes/_authenticated/sujets'
import { Route as ApiPublicVideosRouteImport } from './routes/api/public/videos'
import { Route as ApiVideoContentIdRouteImport } from './routes/api/video-content.$id'
import { Route as ApiPublicJobsRenderCallbackRouteImport } from './routes/api/public/jobs/render-callback'
import { Route as ApiPublicJobsTickRouteImport } from './routes/api/public/jobs/tick'
import { Route as ApiPublicVideosIdRouteImport } from './routes/api/public/videos.$id'

const StationRoute = StationRouteImport.update({
  id: '/station',
  path: '/station',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/_authenticated/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSujetsRoute = AuthenticatedSujetsRouteImport.update({
  id: '/_authenticated/sujets',
  path: '/sujets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVideosRoute = ApiPublicVideosRouteImport.update({
  id: '/api/public/videos',
  path: '/api/public/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoContentIdRoute = ApiVideoContentIdRouteImport.update({
  id: '/api/video-content/$id',
  path: '/api/video-content/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsRenderCallbackRoute =
  ApiPublicJobsRenderCallbackRouteImport.update({
    id: '/api/public/jobs/render-callback',
    path: '/api/public/jobs/render-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsTickRoute = ApiPublicJobsTickRouteImport.update({
  id: '/api/public/jobs/tick',
  path: '/api/public/jobs/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVideosIdRoute = ApiPublicVideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicVideosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/station': typeof StationRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/sujets': typeof AuthenticatedSujetsRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/videos': typeof ApiPublicVideosRouteWithChildren
  '/api/video-content/$id': typeof ApiVideoContentIdRoute
  '/api/public/jobs/render-callback': typeof ApiPublicJobsRenderCallbackRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/videos/$id': typeof ApiPublicVideosIdRoute
}
export interface FileRoutesByTo {
  '/station': typeof StationRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/sujets': typeof AuthenticatedSujetsRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/videos': typeof ApiPublicVideosRouteWithChildren
  '/api/video-content/$id': typeof ApiVideoContentIdRoute
  '/api/public/jobs/render-callback': typeof ApiPublicJobsRenderCallbackRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/videos/$id': typeof ApiPublicVideosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/station': typeof StationRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/sujets': typeof AuthenticatedSujetsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/videos': typeof ApiPublicVideosRouteWithChildren
  '/api/video-content/$id': typeof ApiVideoContentIdRoute
  '/api/public/jobs/render-callback': typeof ApiPublicJobsRenderCallbackRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/videos/$id': typeof ApiPublicVideosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/station'
    | '/parametres'
    | '/sujets'
    | '/'
    | '/api/public/videos'
    | '/api/video-content/$id'
    | '/api/public/jobs/render-callback'
    | '/api/public/jobs/tick'
    | '/api/public/videos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/station'
    | '/parametres'
    | '/sujets'
    | '/'
    | '/api/public/videos'
    | '/api/video-content/$id'
    | '/api/public/jobs/render-callback'
    | '/api/public/jobs/tick'
    | '/api/public/videos/$id'
  id:
    | '__root__'
    | '/station'
    | '/_authenticated/parametres'
    | '/_authenticated/sujets'
    | '/_authenticated/'
    | '/api/public/videos'
    | '/api/video-content/$id'
    | '/api/public/jobs/render-callback'
    | '/api/public/jobs/tick'
    | '/api/public/videos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StationRoute: typeof StationRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedSujetsRoute: typeof AuthenticatedSujetsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  ApiPublicVideosRoute: typeof ApiPublicVideosRouteWithChildren
  ApiVideoContentIdRoute: typeof ApiVideoContentIdRoute
  ApiPublicJobsRenderCallbackRoute: typeof ApiPublicJobsRenderCallbackRoute
  ApiPublicJobsTickRoute: typeof ApiPublicJobsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/station': {
      id: '/station'
      path: '/station'
      fullPath: '/station'
      preLoaderRoute: typeof StationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sujets': {
      id: '/_authenticated/sujets'
      path: '/sujets'
      fullPath: '/sujets'
      preLoaderRoute: typeof AuthenticatedSujetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/videos': {
      id: '/api/public/videos'
      path: '/api/public/videos'
      fullPath: '/api/public/videos'
      preLoaderRoute: typeof ApiPublicVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-content/$id': {
      id: '/api/video-content/$id'
      path: '/api/video-content/$id'
      fullPath: '/api/video-content/$id'
      preLoaderRoute: typeof ApiVideoContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/render-callback': {
      id: '/api/public/jobs/render-callback'
      path: '/api/public/jobs/render-callback'
      fullPath: '/api/public/jobs/render-callback'
      preLoaderRoute: typeof ApiPublicJobsRenderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/tick': {
      id: '/api/public/jobs/tick'
      path: '/api/public/jobs/tick'
      fullPath: '/api/public/jobs/tick'
      preLoaderRoute: typeof ApiPublicJobsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/videos/$id': {
      id: '/api/public/videos/$id'
      path: '/$id'
      fullPath: '/api/public/videos/$id'
      preLoaderRoute: typeof ApiPublicVideosIdRouteImport
      parentRoute: typeof ApiPublicVideosRoute
    }
  }
}

interface ApiPublicVideosRouteChildren {
  ApiPublicVideosIdRoute: typeof ApiPublicVideosIdRoute
}

const ApiPublicVideosRouteChildren: ApiPublicVideosRouteChildren = {
  ApiPublicVideosIdRoute: ApiPublicVideosIdRoute,
}

const ApiPublicVideosRouteWithChildren = ApiPublicVideosRoute._addFileChildren(
  ApiPublicVideosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  StationRoute: StationRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedSujetsRoute: AuthenticatedSujetsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  ApiPublicVideosRoute: ApiPublicVideosRouteWithChildren,
  ApiVideoContentIdRoute: ApiVideoContentIdRoute,
  ApiPublicJobsRenderCallbackRoute: ApiPublicJobsRenderCallbackRoute,
  ApiPublicJobsTickRoute: ApiPublicJobsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
