/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ReinitialisationRouteImport } from './routes/reinitialisation'
import { Route as StationRouteImport } from './routes/station'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEspaceRouteImport } from './routes/_authenticated/espace'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/_admin/index'
import { Route as AuthenticatedAdminParametresRouteImport } from './routes/_authenticated/_admin/parametres'
import { Route as AuthenticatedAdminSujetsRouteImport } from './routes/_authenticated/_admin/sujets'
import { Route as ApiPublicVideosRouteImport } from './routes/api/public/videos'
import { Route as ApiVideoContentIdRouteImport } from './routes/api/video-content.$id'
import { Route as ApiPublicJobsRenderCallbackRouteImport } from './routes/api/public/jobs/render-callback'
import { Route as ApiPublicJobsTickRouteImport } from './routes/api/public/jobs/tick'
import { Route as ApiPublicVideosIdRouteImport } from './routes/api/public/videos.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialisationRoute = ReinitialisationRouteImport.update({
  id: '/reinitialisation',
  path: '/reinitialisation',
  getParentRoute: () => rootRouteImport,
} as any)
const StationRoute = StationRouteImport.update({
  id: '/station',
  path: '/station',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEspaceRoute = AuthenticatedEspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminParametresRoute =
  AuthenticatedAdminParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSujetsRoute =
  AuthenticatedAdminSujetsRouteImport.update({
    id: '/sujets',
    path: '/sujets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicVideosRoute = ApiPublicVideosRouteImport.update({
  id: '/api/public/videos',
  path: '/api/public/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoContentIdRoute = ApiVideoContentIdRouteImport.update({
  id: '/api/video-content/$id',
  path: '/api/video-content/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsRenderCallbackRoute =
  ApiPublicJobsRenderCallbackRouteImport.update({
    id: '/api/public/jobs/render-callback',
    path: '/api/public/jobs/render-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsTickRoute = ApiPublicJobsTickRouteImport.update({
  id: '/api/public/jobs/tick',
  path: '/api/public/jobs/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVideosIdRoute = ApiPublicVideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicVideosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAdminIndexRoute
  '/connexion': typeof ConnexionRoute
  '/reinitialisation': typeof ReinitialisationRoute
  '/station': typeof StationRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/espace': typeof AuthenticatedEspaceRoute
  '/parametres': typeof AuthenticatedAdminParametresRoute
  '/sujets': typeof AuthenticatedAdminSujetsRoute
  '/api/public/videos': typeof ApiPublicVideosRouteWithChildren
  '/api/video-content/$id': typeof ApiVideoContentIdRoute
  '/api/public/jobs/render-callback': typeof ApiPublicJobsRenderCallbackRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/videos/$id': typeof ApiPublicVideosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAdminIndexRoute
  '/connexion': typeof ConnexionRoute
  '/reinitialisation': typeof ReinitialisationRoute
  '/station': typeof StationRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/espace': typeof AuthenticatedEspaceRoute
  '/parametres': typeof AuthenticatedAdminParametresRoute
  '/sujets': typeof AuthenticatedAdminSujetsRoute
  '/api/public/videos': typeof ApiPublicVideosRouteWithChildren
  '/api/video-content/$id': typeof ApiVideoContentIdRoute
  '/api/public/jobs/render-callback': typeof ApiPublicJobsRenderCallbackRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/videos/$id': typeof ApiPublicVideosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/reinitialisation': typeof ReinitialisationRoute
  '/station': typeof StationRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/espace': typeof AuthenticatedEspaceRoute
  '/_authenticated/_admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/_authenticated/_admin/sujets': typeof AuthenticatedAdminSujetsRoute
  '/api/public/videos': typeof ApiPublicVideosRouteWithChildren
  '/api/video-content/$id': typeof ApiVideoContentIdRoute
  '/_authenticated/_admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/jobs/render-callback': typeof ApiPublicJobsRenderCallbackRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/videos/$id': typeof ApiPublicVideosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/reinitialisation'
    | '/station'
    | '/admin'
    | '/espace'
    | '/parametres'
    | '/sujets'
    | '/api/public/videos'
    | '/api/video-content/$id'
    | '/api/public/jobs/render-callback'
    | '/api/public/jobs/tick'
    | '/api/public/videos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/reinitialisation'
    | '/station'
    | '/admin'
    | '/espace'
    | '/parametres'
    | '/sujets'
    | '/api/public/videos'
    | '/api/video-content/$id'
    | '/api/public/jobs/render-callback'
    | '/api/public/jobs/tick'
    | '/api/public/videos/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/connexion'
    | '/reinitialisation'
    | '/station'
    | '/_authenticated/_admin'
    | '/_authenticated/admin'
    | '/_authenticated/espace'
    | '/_authenticated/_admin/parametres'
    | '/_authenticated/_admin/sujets'
    | '/api/public/videos'
    | '/api/video-content/$id'
    | '/_authenticated/_admin/'
    | '/api/public/jobs/render-callback'
    | '/api/public/jobs/tick'
    | '/api/public/videos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  ReinitialisationRoute: typeof ReinitialisationRoute
  StationRoute: typeof StationRoute
  ApiPublicVideosRoute: typeof ApiPublicVideosRouteWithChildren
  ApiVideoContentIdRoute: typeof ApiVideoContentIdRoute
  ApiPublicJobsRenderCallbackRoute: typeof ApiPublicJobsRenderCallbackRoute
  ApiPublicJobsTickRoute: typeof ApiPublicJobsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialisation': {
      id: '/reinitialisation'
      path: '/reinitialisation'
      fullPath: '/reinitialisation'
      preLoaderRoute: typeof ReinitialisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station': {
      id: '/station'
      path: '/station'
      fullPath: '/station'
      preLoaderRoute: typeof StationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace': {
      id: '/_authenticated/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof AuthenticatedEspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/': {
      id: '/_authenticated/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/parametres': {
      id: '/_authenticated/_admin/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedAdminParametresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/sujets': {
      id: '/_authenticated/_admin/sujets'
      path: '/sujets'
      fullPath: '/sujets'
      preLoaderRoute: typeof AuthenticatedAdminSujetsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/videos': {
      id: '/api/public/videos'
      path: '/api/public/videos'
      fullPath: '/api/public/videos'
      preLoaderRoute: typeof ApiPublicVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-content/$id': {
      id: '/api/video-content/$id'
      path: '/api/video-content/$id'
      fullPath: '/api/video-content/$id'
      preLoaderRoute: typeof ApiVideoContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/render-callback': {
      id: '/api/public/jobs/render-callback'
      path: '/api/public/jobs/render-callback'
      fullPath: '/api/public/jobs/render-callback'
      preLoaderRoute: typeof ApiPublicJobsRenderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/tick': {
      id: '/api/public/jobs/tick'
      path: '/api/public/jobs/tick'
      fullPath: '/api/public/jobs/tick'
      preLoaderRoute: typeof ApiPublicJobsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/videos/$id': {
      id: '/api/public/videos/$id'
      path: '/$id'
      fullPath: '/api/public/videos/$id'
      preLoaderRoute: typeof ApiPublicVideosIdRouteImport
      parentRoute: typeof ApiPublicVideosRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminParametresRoute: typeof AuthenticatedAdminParametresRoute
  AuthenticatedAdminSujetsRoute: typeof AuthenticatedAdminSujetsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminParametresRoute: AuthenticatedAdminParametresRoute,
    AuthenticatedAdminSujetsRoute: AuthenticatedAdminSujetsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEspaceRoute: typeof AuthenticatedEspaceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEspaceRoute: AuthenticatedEspaceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicVideosRouteChildren {
  ApiPublicVideosIdRoute: typeof ApiPublicVideosIdRoute
}

const ApiPublicVideosRouteChildren: ApiPublicVideosRouteChildren = {
  ApiPublicVideosIdRoute: ApiPublicVideosIdRoute,
}

const ApiPublicVideosRouteWithChildren = ApiPublicVideosRoute._addFileChildren(
  ApiPublicVideosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  ReinitialisationRoute: ReinitialisationRoute,
  StationRoute: StationRoute,
  ApiPublicVideosRoute: ApiPublicVideosRouteWithChildren,
  ApiVideoContentIdRoute: ApiVideoContentIdRoute,
  ApiPublicJobsRenderCallbackRoute: ApiPublicJobsRenderCallbackRoute,
  ApiPublicJobsTickRoute: ApiPublicJobsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
